In [ ]:
import numpy as np
X = 2 * np.random.rand(100,1)
Y = 4 + 3 * X + np.random.rand(100,1)
#使用Numpy的线性代数模块(np.linalg)中的inv()函数对矩阵求逆
x_b = np.c_[np.ones((100,1)),X]
theta_best = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(Y)
theta_best

In [23]:
'''绘制模型'''
import matplotlib.pyplot as plt
plt.plot(X, Y, 'b.')
plt.plot(X_new, y_predict, 'r-')
plt.axis([0,2,0,15])
plt.show()


array([[7.3297837 ],
       [7.13307199]])

In [ ]:

'''用theta做出预测'''
X_new = np.array([[0],[2]])
X_new_b = np.c_[np.ones((2,1)), X_new]
y_predict = X_new_b.dot(theta_best)
y_predict

In [25]:

'''使用sklearn实现线性回归预测模型'''
from sklearn.linear_model import  LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, Y)
lin_reg.intercept_, lin_reg.coef_
lin_reg.predict(X_new)

array([[7.3297837 ],
       [7.13307199]])

In [28]:
'''梯度下降的快速实现'''
eta = 0.1
n_iterations = 2000
m = 100
theta = np.random.randn(2,1)
for niteration in range(n_iterations):
    gradients = 2 / m * x_b.T.dot(x_b.dot(theta) - Y)
    theta = theta - eta * gradients
theta

array([[4.50765373],
       [2.9553803 ]])

In [30]:
n_epochs = 50
t0, t1 = 5, 50
def learning_schedule(t):
    return  t0 / (t + t1)

theta = np.random.randn(2,1)
for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = x_b[random_index:random_index+1]
        yi = Y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
        eta = learning_schedule(epoch * m + i)
        theta = theta - eta * gradients
theta


array([[4.49175038],
       [2.9674734 ]])

In [34]:
'''SGDRegressor'''
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(n_iter=50, penalty= None, eta0=0.1)
sgd_reg.fit(X,Y.ravel())
sgd_reg.intercept_, sgd_reg.coef_


C:\Users\qianli\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


(array([7.31011648]), array([-0.12077238]))

In [39]:
'''多项式回归'''
m = 100
X = 6 * np.random.rand(m, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)
plt.plot(X, y,'b.')
plt.show()

from sklearn.preprocessing import PolynomialFeatures
# 使用PolynomialFeatures类来对训练数据进行转换，将每个特征的平方作为新特征加入训练集
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X)
X[0]
X_poly[0]


array([-1.99972923,  3.998917  ])

In [40]:
'''对训练集匹配一个LinearRegression模型'''
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y)
lin_reg.intercept_, lin_reg.coef_

(array([2.18550817]), array([[1.07598404, 0.48435605]]))